/**
 * ============================================================================
 * rest — Hooks 理解检验:effect、缓存、自定义 Hook、并发
 * ============================================================================
 *
 * @module topics/hooks/check/rest
 */

import type { CheckQuestion } from '../../../components/check/types';

export const EFFECT_QUESTIONS: readonly CheckQuestion[] = [
    {
        id: 'h-effect-when',
        toc: 'effect 在绘制后',
        title: 'useEffect 里的函数什么时候跑？为什么不适合做首屏唯一的数据来源？',
        note: '先画,再跑。',
        points: ['提交并且浏览器绘制之后才执行。', '服务端渲染不会跑它。', '首屏数据应是渲染输入,effect 适合订阅和浏览器同步。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        body: [
            '界面可以先出现,effect 再去请求。用户会先看到空状态或旧数据。若这份数据就是首屏内容,HTML 或第一次渲染里应该已经有它,而不是等 effect 再抄进 state。',
            '适合 effect 的是:订阅、定时器、和 DOM 以外的系统同步,以及非首屏关键的请求。依赖变了要先清理再重建。',
        ],
    },
    {
        id: 'h-deps',
        toc: '依赖是身份',
        title: '依赖数组比较的是什么？为什么对象和函数写进去会一直重跑？',
        note: '每一项用 Object.is。',
        points: ['依赖是这次渲染读到的值的列表。', '新对象、新函数每次都不相等。', '漏写依赖,effect 会一直用旧的那份。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        difficulty: 3,
        focus: '依赖数组不是自动订阅',
        body: [
            'effect 槽里记着上一次的依赖。有一项 Object.is 失败,就先跑清理,再跑这次的创建。写在函数里现造的对象,每次渲染都是新的,effect 每次都重跑。',
            '把对象移出依赖、改成里面的 id,或把函数用 useCallback 稳住,前提是函数确实需要稳定身份。不要用空数组掩盖「我用到了会变的值」。空数组的意思是只在挂载和卸载时同步。',
        ],
    },
    {
        id: 'h-cleanup',
        toc: '清理先于下一次',
        title: 'effect 的清理函数在什么时候跑？',
        note: '依赖变化和卸载都会跑,而且先销毁再创建。',
        points: ['下一次要重跑时,先跑上一次返回的清理。', '卸载时只清理,不再创建。', 'StrictMode 开发环境会多一次创建、清理、再创建。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        difficulty: 3,
        focus: '订阅泄漏和开发环境双请求',
        body: [
            '清理用来放开监听、定时器和订阅。它不应该假设自己的 DOM 还在布局里。绘制后才跑的清理,节点可能已经摘掉。',
            '开发环境多出来的那次是在模拟卸载,用来暴露没写清理的监听。生产不会为了检查而双调用。看到请求两次,先确认是不是这次模拟,再决定要不要改。',
        ],
    },
    {
        id: 'h-no-effect-event',
        toc: '点击不要绕进 effect',
        title: '为什么「按钮点击」不该写成 setClicked 再在 effect 里发请求？',
        note: '由事件引起的事放在事件里。',
        points: ['effect 会因为依赖里别的值再跑,请求可能重复。', '事件函数里直接发请求,时机就是这次点击。', 'effect 响应的是渲染结果和外系统的同步,不是用户动作的替身。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        difficulty: 4,
        focus: '事件和 effect 的职责',
        body: [
            '用一个布尔值触发 effect,等于把点击翻译成渲染,再从渲染翻译成请求。主题、路由一变,如果也在依赖里,请求会再走一遍。',
            '点击处理函数里能读到这次的参数,也能 catch 错误、中止上一次。这些都不要绕一圈 state。state 只保留请求结果和是否进行中,如果界面需要显示它们。',
        ],
    },
    {
        id: 'h-race',
        toc: '请求竞态',
        title: '快速改了两次关键字,为什么慢的那次响应可能覆盖新的结果？',
        note: 'effect 不会自动丢弃过期响应。',
        points: ['先发出的请求可能后返回。', '清理里忽略过期响应,或用 AbortController 取消。', '只看最后一次渲染对应的那次结果。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        difficulty: 4,
        focus: '异步 effect 的过期写入',
        body: [
            '关键字从 a 改到 b,a 的响应如果更慢,它回来时会把 b 的结果盖掉。清理函数在关键字变化时运行,把上一次标记为过期,过期的 then 里不要 setState。',
            '能取消的请求用 AbortController,在清理里 abort。取消失败的错误要和真正的失败分开,不要弹一次「请求出错」。',
        ],
    },
    {
        id: 'h-strict-fetch',
        toc: '开发环境打两次',
        title: 'StrictMode 下 effect 里的请求打了两次,生产也会吗？',
        note: '开发期的可重入检查。',
        points: ['开发环境挂载时会执行、清理、再执行。', '生产只保留一次挂载。', '没有清理的订阅会在开发时变成两个。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        difficulty: 3,
        focus: '双调用是检查,不是生产模型',
        body: [
            '请求如果在 effect 里,开发时会看到两次。清理里 abort 掉第一次,第二次才是留下的。这样生产的一次挂载也有正确的清理路径。',
            '不要为了消掉开发日志关掉 StrictMode。重复说明渲染或 effect 不纯,或者清理没把外部资源放开。',
        ],
    },
    {
        id: 'h-external-store',
        toc: '订阅外部 store',
        title: '为什么订阅浏览器 API 或外部 store,优先 useSyncExternalStore,而不是 effect 里 setState？',
        note: 'effect 订阅会晚一帧,还可能撕裂。',
        points: ['effect 在绘制后才订阅,第一帧用的是猜测值。', 'useSyncExternalStore 在渲染时读取当前快照。', '服务端和客户端的快照要分别给出,避免水合不一致。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        difficulty: 5,
        focus: '外部事实如何进入渲染',
        body: [
            '在 effect 里订阅然后 setState,提交的第一帧往往是默认值,然后再跳到真实值。并发渲染下,还可能读到一次渲染中途被外部改掉的值。',
            'useSyncExternalStore 要求你提供 getSnapshot 和 subscribe。React 在渲染时读快照,在外部变化时再渲染。getSnapshot 必须返回稳定身份:没变就返回同一个值,否则会循环渲染。',
        ],
    },
    {
        id: 'h-effect-deps-fn',
        toc: '函数进依赖',
        title: 'effect 依赖了一个每次都会新建的函数,有哪些正经的收法？',
        note: '先问这个函数该不该进依赖。',
        points: ['函数用到了渲染里的值,它就该被看见。', '用 useCallback 稳住,依赖是它真正读到的值。', '只在调用时才需要最新回调、又不想重订阅,用 useEffectEvent。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        difficulty: 5,
        focus: '依赖、稳定回调、effect 事件三者的差别',
        body: [
            '把函数排除出依赖,effect 会调用旧函数,读到旧 props。这是漏依赖,不是优化。useCallback 让函数身份跟着真正的输入走,输入没变,effect 不重跑。',
            '订阅本身只该在 roomId 变化时重建,但回调要在通知时看到最新的主题。这种「订阅的身份」和「回调的最新值」可以分开:effect 依赖 roomId,回调用 useEffectEvent 包一层,事件函数不放进依赖数组。不要把普通会变的数据也塞进 effect 事件来逃避依赖。',
        ],
    },
    {
        id: 'h-mount-once',
        toc: '空依赖不是只运行一次的保证',
        title: 'useEffect(fn, []) 能保证整个应用生命周期只跑一次吗？',
        note: '空数组是「这个组件挂载期间」。',
        points: ['组件卸载再挂载会再跑。', '开发环境 StrictMode 会多跑一次清理循环。', '应用级初始化不要放在一个会被反复挂上的组件里。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        difficulty: 4,
        focus: '挂载和一次应用启动不是一回事',
        body: [
            '路由一走,组件卸了,再进来又是一次挂载,空依赖的 effect 再跑。它保证不了进程级只一次。',
            '真要在应用启动时做一次,放在入口模块,并用模块级标记挡住开发环境的重复挂载。不要把这种初始化写进一个列表项组件。',
        ],
    },
    {
        id: 'h-set-state-effect',
        toc: 'effect 里同步派生',
        title: '为什么不要在 effect 里把 props 同步进 state？',
        note: '多一次渲染,还多一段不一致。',
        points: ['能算出来的值在渲染时算。', 'effect 同步会先提交旧副本。', '用户草稿才是独立 state,重置要显式。'],
        related: [{ to: '/hooks/use-effect', label: 'useEffect' }],
        difficulty: 3,
        focus: '派生状态',
        body: [
            'fullName 这种值没有自己的生命周期。effect 里 setFullName,用户会先看到空,再看到算好的名字。渲染时直接拼接就没有这段空隙。',
            '表单初始值来自服务器、之后要让用户改,那是草稿。用 key 在数据身份变化时重置组件,比在 effect 里无条件覆盖用户输入更清楚。',
        ],
    },
];

export const LAYOUT_QUESTIONS: readonly CheckQuestion[] = [
    {
        id: 'h-layout-vs-effect',
        toc: '绘制前还是绘制后',
        title: 'useLayoutEffect 和 useEffect 的缝在哪？',
        note: '绘制夹在两者之间。',
        points: ['layout 在 DOM 更新后、绘制前同步执行。', 'passive 在绘制后。', '量完必须在这一帧改位置,用 layout。'],
        related: [{ to: '/hooks/use-layout-effect', label: 'useLayoutEffect' }],
        body: [
            'useLayoutEffect 里读到的是新 DOM,像素还没画。这里 setState 会在绘制前再走一轮,用户看不到中间帧,主线程更长。',
            '请求、日志、订阅放 useEffect,让这一帧先出来。用 effect 做「先量再挪」,用户会看到跳一下。',
        ],
    },
    {
        id: 'h-layout-ssr',
        toc: '服务端警告',
        title: '为什么服务端渲染时出现 useLayoutEffect 会警告？',
        note: '服务端没有布局可读。',
        points: ['服务端执行不了布局读取。', '客户端水合后再跑,可能把已经写出的界面再改一次。', '不依赖布局的逻辑不要放在这里。'],
        related: [{ to: '/hooks/use-layout-effect', label: 'useLayoutEffect' }],
        difficulty: 3,
        focus: 'SSR 和布局 effect 的空隙',
        body: [
            '服务端只产出 HTML,没有盒模型。useLayoutEffect 被跳过,客户端再执行,如果它改了文本或位置,水合之后会闪。',
            '能在两端算出相同结果的东西不要放进 layout。必须读 DOM 的校正留在客户端,并让服务端写出的那份内容经得起这一下校正。',
        ],
    },
    {
        id: 'h-insertion',
        toc: '样式注入更早',
        title: 'useInsertionEffect 和 useLayoutEffect 谁更早？给谁用？',
        note: '它是样式库的缝,不是业务里的另一个 layout。',
        points: ['insertion 在 mutation 阶段,早于 layout 读尺寸。', '给 CSS-in-JS 在量布局之前插入 style。', '不要在里面 setState 或读布局。'],
        related: [{ to: '/internals/commit', label: 'Commit' }],
        difficulty: 4,
        focus: '三条 effect 的顺序',
        body: [
            '如果样式等到 layout 才插入,量到的是没样式的盒子,然后再插入,布局会跳。insertion 把这件事提前。',
            '业务代码停在 layout 或 effect。只有库在做「样式必须先于布局读取」时才用 insertion。',
        ],
    },
    {
        id: 'h-layout-set',
        toc: 'layout 里 setState 的代价',
        title: '在 useLayoutEffect 里 setState,用户为什么常常看不到中间帧？代价是什么？',
        note: '同步再渲染,绘制被推迟。',
        points: ['此时还在绘制前,更新按同步做完。', '能消掉闪烁。', '主线程上会连续两段提交。'],
        related: [{ to: '/hooks/use-layout-effect', label: 'useLayoutEffect' }],
        difficulty: 4,
        focus: '消除闪烁和挡住这一帧的交换',
        body: [
            '第一轮写进 DOM 的值如果在 layout 里又被改掉,浏览器还没画第一轮,用户只看到第二轮。这适合工具提示算完坐标再出现。',
            '在这里发请求或做大计算,点击之后的那一帧要等它结束。请求放 effect。能在渲染时算完的位置,不要等 layout 再 setState。',
        ],
    },
];

export const MEMO_QUESTIONS: readonly CheckQuestion[] = [
    {
        id: 'h-memo-what',
        toc: 'useMemo 记住什么',
        title: 'useMemo 在什么条件下重新计算？',
        note: '依赖比较是 Object.is,不是深比较。',
        points: ['槽里存着上一次的值和依赖。', '任一项依赖身份变了就重算。', '它不让计算变快,只是输入没变时跳过。'],
        related: [{ to: '/hooks/use-memo', label: 'useMemo' }],
        body: [
            '计算本身很贵,而且输入经常不变,才值得记住。便宜的表达式包一层,比较依赖的成本可能更高。',
            '依赖漏写,会一直交回旧结果。依赖写成每次新的对象,会每次都重算,useMemo 等于没写。',
        ],
    },
    {
        id: 'h-callback',
        toc: 'useCallback 稳住的是函数',
        title: 'useCallback 和 useMemo 差在哪？它能减少函数内部的执行吗？',
        note: '稳住的是引用,不是调用次数。',
        points: ['useCallback(fn, deps) 记住函数本身。', '函数被调用时,该跑的逻辑仍会跑。', '它的意义是让子组件的浅比较能够成功。'],
        related: [{ to: '/hooks/use-callback', label: 'useCallback' }],
        body: [
            '子组件用 memo 包着,props 里有一个每次新建的回调,浅比较失败,子组件照样渲染。useCallback 让回调在依赖不变时保持同一引用。',
            '没有 memo 的子组件不看引用。给每个函数都包 useCallback,只增加槽位和比较,渲染次数不会因此下降。先确定有没有人在比较这个引用。',
        ],
    },
    {
        id: 'h-memo-child',
        toc: 'memo 比较发生在调用前',
        title: 'memo 跳过的是什么？什么样的 props 会让它失效？',
        note: '比较在执行函数之前,默认浅比较。',
        points: ['props 每一项 Object.is 相等才跳过函数。', 'children、对象字面量、内联函数经常使比较失败。', '子树里有待处理更新时,不能因为 props 没变就整棵跳过。'],
        related: [{ to: '/hooks/use-memo', label: 'useMemo' }],
        difficulty: 4,
        focus: '跳过渲染的条件是否真的成立',
        body: [
            'memo 失败的常见原因不是算法,是调用处每次都写了新 props。style={{}}、onClick={() => {}}、children 里新的元素,都会让比较失败。',
            '即便比较成功,如果这棵子树里有自己的 setState 还没处理,协调器仍要走进去。memo 不是「这个组件永远不渲染」。',
        ],
    },
    {
        id: 'h-premature',
        toc: '不要从 memo 开始',
        title: '为什么不能把 useMemo、useCallback、memo 当成默认写法？',
        note: '先删掉不必要的工作。',
        points: ['它们是条件成立之后的跳过,不是免费加速。', '比较和槽位本身有成本。', '先看是不是状态放太高、渲染里做了不该做的事。'],
        related: [
            { to: '/hooks/use-memo', label: 'useMemo' },
            { to: '/performance/governance-guide', label: '性能原则' },
        ],
        difficulty: 3,
        focus: '优化顺序',
        body: [
            '一个输入框的 state 放在页面根上,整页都渲染。给每个子组件包 memo,是在给错误的状态位置打补丁。把 state 放回输入框,下面的列表根本不会因为击键而接收新 props。',
            '真的有昂贵子树,而且 props 可以稳住,再 memo。验收看交互是否更跟手,不看渲染次数本身。',
        ],
    },
    {
        id: 'h-usecallback-deps',
        toc: '回调的依赖',
        title: 'useCallback 的依赖漏了会怎样？',
        note: '稳定的是旧函数,不是正确的函数。',
        points: ['漏掉的值一直是创建那次的快照。', '子组件拿到的回调行为过时。', '依赖应是函数里读到的渲染值。'],
        related: [{ to: '/hooks/use-callback', label: 'useCallback' }],
        difficulty: 3,
        focus: '稳定引用和正确性一起成立',
        body: [
            '空依赖的回调永远调用第一版。它把旧的 id 发给接口,界面却显示着新的 id。这比多渲染一次更糟。',
            '依赖写全之后身份会变,这是对的。如果因此打破了子组件 memo,再考虑把用到的值收窄,而不是删依赖。',
        ],
    },
    {
        id: 'h-memo-children',
        toc: 'children 打破 memo',
        title: '为什么 <MemoChild><span /></MemoChild> 经常让 memo 失效？',
        note: 'children 也是 props。',
        points: ['每次渲染的 JSX 都是新元素。', 'memo 比较 children 时 Object.is 失败。', '孩子若由父组件创建一次再作为 children 传入,引用可以保持。'],
        related: [{ to: '/hooks/use-memo', label: 'useMemo' }],
        difficulty: 4,
        focus: '元素身份',
        body: [
            '写在标签中间的内容就是 children。父组件每次执行,这个元素都新建一次,MemoChild 的 props 变了,函数照样跑。',
            '若孩子真的不变,让更上层创建它并通过 children 传下来,中间层原样放下。这是组合,不是再包一个 useMemo 去记住一段 JSX 那么简单,但记住静态元素有时确实能稳住引用。',
        ],
    },
    {
        id: 'h-compiler',
        toc: '编译器没有废除依赖',
        title: 'React Compiler 会让手写的 useMemo 都变成多余吗？规则还在吗？',
        note: '它在构建时帮你遵守规则。',
        points: ['编译结果仍然按固定顺序调用 Hook。', '自动记忆化是为了让跳过渲染的条件成立。', '运行时次数变化的 Hook 仍然不合法。'],
        related: [{ to: '/internals/hooks-impl', label: 'Hooks 链表' }],
        difficulty: 4,
        focus: '编译优化和链表身份是两层',
        body: [
            'Compiler 看控制流,把缓存插进去,让你少写一些 useCallback。运行时仍用调用顺序取槽。它不是按变量名找到 state。',
            '条件里调用 useState,编译器会拒绝或改写。不要把它理解成规则消失了。use 可以条件调用,是因为它不占这种槽,和编译器无关。',
        ],
    },
    {
        id: 'h-inline-default',
        toc: '默认参数破坏 memo',
        title: '为什么 memo 组件的默认参数如果是新对象或新函数,会让 memo 失效？',
        note: '默认值在调用时创建。',
        points: ['参数缺省时,默认表达式每次得到新值。', '浅比较因此失败。', '把默认值提成模块级常量。'],
        related: [{ to: '/hooks/use-memo', label: 'useMemo' }],
        difficulty: 3,
        focus: '引用在哪一次被新建',
        body: [
            'function Item({ onClick = function () {} }) 每次渲染都造一个新函数,即便父组件没传 onClick。memo 看见的 props 每次不同。',
            '模块顶层写一个空函数常量,默认参数指向它。数组和对象默认值同样提出去。这样「没传」在每次渲染里是同一个值。',
        ],
    },
];

export const CUSTOM_QUESTIONS: readonly CheckQuestion[] = [
    {
        id: 'h-custom-slot',
        toc: '自定义 Hook 不占单独节点',
        title: '自定义 Hook 在状态树上有自己的节点吗？',
        note: '它是函数,里面的每个 Hook 仍占调用方的槽。',
        points: ['没有名叫这个 Hook 的 Fiber。', '内部的 useState 按顺序接在组件链表上。', '两个组件调用它,得到两份状态。'],
        related: [{ to: '/hooks/custom-hooks-guide', label: '自定义 Hooks' }],
        body: [
            '自定义 Hook 只是把一组调用收进一个函数。条件调用它,后面的槽全错。规则和组件一样。',
            '复用的是行为,不是一份共享 state。要共享,把状态放到共同父级、Context 或外部 store。',
        ],
    },
    {
        id: 'h-custom-name',
        toc: '为什么以 use 开头',
        title: '自定义 Hook 为什么必须以 use 开头？里面为什么只能调用 Hook？',
        note: '名字是给检查工具和读者的约定。',
        points: ['use 开头让 lint 按 Hook 规则检查它。', '普通函数里调用 useState,调用次数无法保证。', '它应该把一类有状态的行为收口,而不是包一层 JSX。'],
        related: [{ to: '/hooks/custom-hooks-guide', label: '自定义 Hooks' }],
        body: [
            '检查工具靠名字识别 Hook。不以 use 开头,条件调用也不会被提醒,错位要到运行时才出现。',
            '如果函数只是算一个值、没有状态和订阅,它就是普通函数,不要叫 use。如果它返回的是一大段 JSX 加十个没关联的状态,它应该是组件,不是 Hook。',
        ],
    },
    {
        id: 'h-custom-return',
        toc: '返回值要稳定',
        title: '自定义 Hook 每次返回新对象,会给调用方带来什么问题？',
        note: '返回值的身份会变成别人的依赖。',
        points: ['调用方把返回值放进依赖,对象每次都是新的。', '能返回元组或稳定字段,就不要包一个新对象。', '必须返回对象时,用 useMemo 稳住,依赖是里面的值。'],
        related: [{ to: '/hooks/custom-hooks-guide', label: '自定义 Hooks' }],
        difficulty: 3,
        focus: 'Hook 的返回身份',
        body: [
            'return { count, inc } 每次都是新对象。调用方 useEffect 依赖整个对象,effect 每次跑。调用方其实只需要 count 和 inc 两个名字。',
            '返回数组可以让调用方自己命名,也避免无意义的包装对象。若 API 就是对象,记住它,并且依赖写全。',
        ],
    },
    {
        id: 'h-compose',
        toc: '分层组合',
        title: '领域 Hook 应该怎么调用原子 Hook,而不是把请求、防抖和状态写进一个函数？',
        note: '一层只做一种事,组合发生在上一层。',
        points: ['原子 Hook 管一件事:请求、事件、布尔开关。', '领域 Hook 把它们按业务顺序拼起来。', '不要在领域 Hook 里复制原子 Hook 已经有的清理逻辑。'],
        related: [{ to: '/hooks/custom-hooks-composition', label: '组合实战' }],
        difficulty: 3,
        focus: '组合而不是复制',
        body: [
            '搜索可以是:输入 state、防抖、请求、竞态取消,四段都已有原子实现。领域 Hook 把关键字推进去,把结果读出来。每一段可以单独测。',
            '把这些全部写进 useUserSearch 的一个 effect,下一次做别的搜索还要再抄一遍,清理和竞态很容易漏。组合的代价是多几个函数名,换来的是每一层都能单独看懂。',
        ],
    },
    {
        id: 'h-conditional-hook',
        toc: '不能条件调用',
        title: '为什么 if 里面不能调用 useState？use 为什么可以？',
        note: '身份是第几次调用。',
        points: ['更新时按序号取链表上的槽。', '中间多一次调用,后面的 Hook 读到别人的状态。', 'use 不占这种槽,所以可以写在条件里。'],
        related: [{ to: '/internals/hooks-impl', label: 'Hooks 链表' }],
        difficulty: 4,
        focus: '槽位身份和 use 的例外',
        body: [
            '第一次渲染把 Hook 节点接到链表尾。以后从头部按次数取。条件成立才多一个 useState,后面的 effect 会读到数字或 ref,类型已经错了。循环里调用也不安全,除非次数永远不变。',
            'React 19 的 use 读 Context 或解开 Promise,不往这条链表追加 useState 那种槽。其它 Hook 没有这条豁免。',
        ],
    },
    {
        id: 'h-keys-reset',
        toc: '用 key 重置 Hook',
        title: '同一个组件想把内部 state 全部回到初始值,应该怎么做？',
        note: '换身份,而不是在 effect 里逐个 set。',
        points: ['改 key,React 卸载旧实例、挂上新实例。', '新实例的 useState 从初始值再来。', '逐个重置容易漏,也会和用户正在进行的输入打架。'],
        related: [{ to: '/hooks/custom-hooks-guide', label: '自定义 Hooks' }],
        difficulty: 3,
        focus: '状态的生命周期跟着谁',
        body: [
            '用户切换了 id,表单仍留着上一个人的草稿,是因为组件实例没换,Hook 链表还在。父组件把 key 设成 id,切换时整段状态一起走。',
            '这会跑卸载清理和新的 effect。若只是一个字段要清空,直接 set。不要为了清一个输入框把整棵子树拆掉。',
        ],
    },
    {
        id: 'h-rules-lint',
        toc: '规则检查',
        title: 'eslint 的 Hook 规则在防什么？关掉它会怎样？',
        note: '规则保护的是链表,不是风格。',
        points: ['它检查 Hook 是否在每次渲染以同样的顺序调用。', '关掉之后错位变成运行时才出现的串状态。', '编译器和 lint 都遵守这条,不代替这条。'],
        related: [{ to: '/hooks/custom-hooks-guide', label: '自定义 Hooks' }],
        body: [
            '在条件、循环、普通函数里调用 Hook,下一次渲染可能对不上槽。表现是 state 串了、effect 跑错,而不是一条明确的语法错误。',
            '规则也会提醒依赖。那部分可以逐条判断是不是误报,但「不要条件调用」几乎没有例外。use 是唯一明确的条件读取 API。',
        ],
    },
    {
        id: 'h-custom-test',
        toc: 'Hook 怎么测',
        title: '自定义 Hook 应该测行为,还是测它内部用了几次 useState？',
        note: '调用方看得见的是返回值和清理。',
        points: ['用 renderHook 或一个很小的宿主组件驱动它。', '断言返回值、重渲染和卸载清理。', '不要断言槽位数量,那是实现细节。'],
        related: [{ to: '/hooks/custom-hooks-playground', label: '原子演练' }],
        body: [
            '测试把初始 props 传进去,触发返回的更新函数,看下一次的值。异步请求看成功、失败和卸载之后不再写入。',
            '内部从 useState 换成 useReducer,只要行为不变,测试就该继续通过。测调用次数会把重构锁死。',
        ],
    },
];

export const CONCURRENT_QUESTIONS: readonly CheckQuestion[] = [
    {
        id: 'h-transition',
        toc: 'transition 改的是优先级',
        title: 'startTransition 包住 setState 之后,界面为什么还能先响应输入？',
        note: '紧急更新先提交,过渡更新可以让出。',
        points: ['过渡里的更新不挡住同步输入。', 'isPending 表示结果还没提交。', '它不把任意大计算切成 5 毫秒。'],
        related: [{ to: '/performance/transition-deferred', label: 'transition × deferred' }],
        difficulty: 4,
        focus: '哪些更新可以慢,哪些必须跟手',
        body: [
            '输入框的 setState 留在过渡外面,列表过滤放进过渡。击键先出现,列表可以略旧。isPending 用来显示待定,不是「函数还在执行」的锁。',
            '一个组件函数本身要算很久,让出只能发生在它返回之后。过渡不是自动切片的 API。切片单位是组件树的节点。',
        ],
    },
    {
        id: 'h-deferred',
        toc: 'deferred 推迟的是值',
        title: 'useDeferredValue 和 startTransition 怎么选？',
        note: '一个推迟值的那次渲染,一个标记你发起的更新。',
        points: ['你能包住 setState,用 transition。', '你只拿到一个已经变了的值,用 deferred。', '两者都可能短暂显示新旧并存。'],
        related: [{ to: '/performance/transition-deferred', label: 'transition × deferred' }],
        difficulty: 4,
        focus: '更新的发起点和消费点',
        body: [
            '输入 state 在你手里,把昂贵的 setState 放进 startTransition。上游已经把新关键字传下来,你控制不了那次 setState,就用 useDeferredValue 让昂贵子树先用旧值。',
            '不要把 deferred 用在受控输入本身。输入回显必须是同步的最新值,延迟的是结果列表。',
        ],
    },
    {
        id: 'h-use-promise',
        toc: 'use 可以条件调用',
        title: 'use(promise) 和 useEffect 请求有什么差别？',
        note: '一个在渲染中读取,一个在提交后执行。',
        points: ['未完成时 use 会挂起,由 Suspense 显示后备。', '完成后从缓存读,不占 useState 槽。', '获取动作要能重入,不能每次渲染都发一个无法去重的请求。'],
        related: [{ to: '/internals/hooks-impl', label: 'Hooks 链表' }],
        difficulty: 5,
        focus: '渲染中的读取和提交后的副作用',
        body: [
            '组件执行到 use(promise),Promise 还没完,就抛出给最近的 Suspense。数据好了再从边界重试。首屏可以先出骨架,而不是先出空再在 effect 里补。',
            '因为渲染会重做,开始请求的地方要在缓存里,命中就不要再发。effect 请求则是提交之后的事,适合不是渲染输入的同步。两者不要叠成两套事实。',
        ],
    },
    {
        id: 'h-action',
        toc: 'Action 不是新状态机',
        title: 'useActionState 和 useOptimistic 位于哪一层？',
        note: '它们是过渡上的协议,不是另一套渲染。',
        points: ['Action 把一次提交包成可以等待的过渡。', 'pending 来自结果还没提交。', '乐观更新是 pending 期间的临时 state,失败要能撤。'],
        related: [{ to: '/performance/transition-deferred', label: 'transition × deferred' }],
        difficulty: 5,
        focus: '异步提交和乐观界面',
        body: [
            '表单 action 可以是异步函数。输入不必等网络,按钮可以用 pending 禁用。函数结束再把真实结果提交上去。槽位仍是普通 Hook。',
            'useOptimistic 在等待期间先把评论插进列表。请求失败,临时值撤掉。它不跳过服务器,也不新开一条协调路径。',
        ],
    },
    {
        id: 'h-id',
        toc: 'useId',
        title: '为什么无障碍 id 用 useId,而不用 Math.random 或下标？',
        note: '服务端和客户端要得到同一个 id。',
        points: ['useId 在一次渲染树里稳定,两端一致。', '随机值会导致水合对不上。', '它不是列表 key,也不是业务 id。'],
        related: [{ to: '/hooks/use-state', label: 'useState' }],
        difficulty: 3,
        focus: '稳定且可水合的标识',
        body: [
            'label 的 htmlFor 和输入框 id 必须相同。服务端写出的 id 和客户端第一次渲染的 id 不同,水合会报不匹配。useId 按组件在树中的位置生成,两端一致。',
            '不要用它当列表 key 或数据库 id。列表身份来自数据。useId 在条件渲染改变位置时也会变,它不是业务主键。',
        ],
    },
    {
        id: 'h-context-hook',
        toc: 'useContext 的重渲染',
        title: 'useContext 的值变了,中间组件会自动跳过吗？',
        note: '消费者会更新。跳过中间层要另做。',
        points: ['Provider 用 Object.is 比较 value。', '中间组件默认仍会渲染。', 'children 槽或 memo 才能跳过不关心的那一层。'],
        related: [{ to: '/advanced/context', label: 'Context API' }],
        difficulty: 4,
        focus: 'Context 的更新范围',
        body: [
            'value 写成对象字面量,每次渲染都是新引用,所有消费者都更新,即使字段没变。把 value 用 useMemo 稳住,依赖是真正的字段。',
            '中间层跳过不是 Context 的默认行为。让父组件创建昂贵子树作为 children 传入,中间层原样放下,子元素引用不变才可能跳过。',
        ],
    },
    {
        id: 'h-state-vs-ref-render',
        toc: '频繁值放哪',
        title: '鼠标位置这种高频值,应该放进 state 吗？',
        note: '要画出来才用 state。',
        points: ['每次 mousemove 都 setState,会按这个频率渲染。', '只在事件里读、不画到 React 树,放 ref。', '真要画,就降低频率或标成可延迟的更新。'],
        related: [{ to: '/hooks/use-ref', label: 'useRef' }],
        difficulty: 4,
        focus: '渲染频率和数据用途',
        body: [
            '跟随光标的小圆点如果用 React state 驱动,每移动一像素都可能渲染一棵子树。把位置写进 ref,再用 DOM 直接改 transform,React 不参与每一次移动。',
            '若业务就是「坐标要显示在一段文字里」,那是渲染输出,用 state,但不要让整页订阅它。把显示坐标的叶子收小,必要时用过渡让旁边的重区域晚一点跟上。',
        ],
    },
    {
        id: 'h-stale-bug',
        toc: '过期闭包怎么认',
        title: '怎样判断一个 bug 是过期闭包,而不是批处理？',
        note: '看读到的值属于哪一次渲染。',
        points: ['批处理:同一次事件里的直接更新互相覆盖。', '过期闭包:稍后执行的函数看见创建时的快照。', '前者用函数式更新,后者还要处理依赖或 ref。'],
        related: [{ to: '/hooks/use-state', label: 'useState' }],
        difficulty: 5,
        focus: '两种「不是最新值」的不同原因',
        body: [
            '同一次点击里两次 setCount(count + 1) 只加 1,是批处理和覆盖,函数还没结束,没有「过期」,只是两次读了同一次快照。',
            '定时器、订阅、没写进依赖的 effect 在以后才跑,那时组件可能又渲染过。函数仍拿着旧绑定。修法是函数式更新、补依赖,或在需要最新值的命令式代码里读 ref。不要把两种情况都叫成批处理没生效。',
        ],
    },
];
