/**
 * ============================================================================
 * bank — 进阶专题理解检验
 * ============================================================================
 *
 * 通信通道、Context、错误边界、组合和数据边界。难题标难度和考察点。
 *
 * @module topics/advanced/check/bank
 */

import { countQuestions, numberGroups } from '../../../components/check/numberGroups';
import type { CheckGroup } from '../../../components/check/types';

const GROUPS: readonly CheckGroup[] = [
    {
        id: 'g-comm',
        title: '通信通道',
        blurb: '先问这份事实归谁、要传多远、变得有多勤,再选最矮的通道。',
        questions: [
            {
                id: 'a-owner',
                toc: '事实归谁',
                title: '两个组件要一起用一份数据时,第一步问什么？',
                note: '先定所有权,再谈 props 或 Context。',
                points: ['谁拥有这份事实,谁在渲染里读它。', '只有一个所有者,其它地方接收或上报意图。', '两处各存一份再互相同步,会不一致。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                body: [
                    '选中项、过滤条件、草稿,先决定哪一层是源头。源头改变,别人通过 props 或订阅看到。两边都 useState 再 effect 互相同步,中间一定有一帧是矛盾的。',
                    '子组件可以有自己的瞬时 UI 状态。一旦兄弟也要读,它就不再是私有的,要抬到最近的公共父级。',
                ],
            },
            {
                id: 'a-ladder',
                toc: '通道梯子',
                title: 'props、组合、Context、URL、外部 store,默认先试哪一档？',
                note: '从近到远,能用矮的就不用高的。',
                points: ['父子之间默认 props 向下、回调向上。', '中间层不关心,用 children 组合,而不是层层转发。', '远、稳、读者多,才开 Context。要分享和回退,放进 URL。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 3,
                focus: '通道选择而不是 API 熟悉度',
                body: [
                    '钻探是把中间不关心的 props 一层层传下去。那些中间组件因此要改签名,还跟着渲染。组合让叶子在创建它的那一层拿到数据,外壳只放下 children。',
                    'Context 适合主题、当前用户这种读的人多、变得不勤的值。过滤条件若要能被链接分享,URL 才是事实,Context 只是缓存就会和地址栏打架。高频、树外、多订阅者,用外部 store。',
                ],
            },
            {
                id: 'a-callback',
                toc: '子组件上报意图',
                title: '为什么子组件不该直接改父级的 state？',
                note: '子组件发出意图,父组件决定怎么改。',
                points: ['父组件拥有 state,更新逻辑留在父组件。', '子组件调用 onSelect(id) 这类回调。', '把 setState 原样传下去,子组件会开始依赖父级的数据结构。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                body: [
                    'onChange(id) 让子组件只知道「用户选了这个」。父组件可以把它写成选中项、写进 URL 或发给请求。子组件不用知道后面是哪一种。',
                    '把 setState 传进子组件,子组件就开始拼接父级的对象形状。父级一改结构,所有子组件一起改。回调把这个耦合收在边界上。',
                ],
            },
            {
                id: 'a-lift',
                toc: '提升到最近父级',
                title: '兄弟组件要共享状态,为什么不是互相 ref,也不是各自请求再对齐？',
                note: '提升到最近公共父级。',
                points: ['一个所有者,两份 props。', 'ref 互读不参与渲染,画面不会跟着走。', '各自请求会有两份进度和两份错误。'],
                related: [{ to: '/advanced/component-comm-playground', label: '通信演练' }],
                difficulty: 3,
                focus: '共享事实只有一个源头',
                body: [
                    '列表和详情要看同一个选中 id。id 放在包住两者的父级,列表上报,详情读取。这是同一棵树上的数据流。',
                    '用 ref 让兄弟偷偷读对方的变量,读的时候没有渲染,写的时候对方也不知道。两个人各发一次请求再对 id,失败和加载会各说各话。',
                ],
            },
            {
                id: 'a-url',
                toc: 'URL 是事实',
                title: '什么状态应该放进 URL,而不是只放在 useState？',
                note: '要能分享、刷新和回退的,就是导航状态。',
                points: ['过滤、分页、当前 id 这类状态,刷新后用户还指望还在。', 'URL 是这份事实的源头,组件从查询参数读。', '悬停、输入草稿、弹层动画不要放进地址栏。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 3,
                focus: '哪些状态属于导航',
                body: [
                    '把过滤只放在 state 里,链接无法复现,后退也不会回到上一组条件。查询参数变了,渲染按新参数走,这和 props 变化是同一类更新。',
                    '地址栏是用户看得见的 API。不要把密码、体积很大的草稿或每像素都变的值放进去。那些不是用来分享的。',
                ],
            },
            {
                id: 'a-store',
                toc: '什么时候离开 React 树',
                title: '外部 store 适合什么状态？和 Context 差在哪？',
                note: '树外、高频、订阅者要能各取所需。',
                points: ['Context 变了,消费者这条路径要走一遍。', '外部 store 可以让组件只订阅一个字段。', '不要把只在一棵小树里用的状态搬出去。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 4,
                focus: '订阅粒度',
                body: [
                    '选中、连接状态、播放进度可能被很多不相关的组件读,而且变得勤。放在 Context 里,value 一变,所有 useContext 的组件都要看一遍。store 加选择器可以只让读到那一个字段的组件渲染。',
                    '一个对话框里的表单没有这个需求。搬进全局 store 会让生命周期难懂:对话框关了,store 里的草稿还在。所有权跟着功能走,不跟着「能不能全局访问」走。',
                ],
            },
            {
                id: 'a-command',
                toc: '命令不是数据',
                title: 'focus、scroll、play 为什么用 ref,而不要做成 state？',
                note: '命令是一次动作,不是一份要渲染的事实。',
                points: ['动作用命令句柄表达。', 'state 表示现在是什么,会进入渲染。', '父组件反复 setFocus(true) 是在用数据模拟命令。'],
                related: [{ to: '/hooks/use-imperative-handle', label: '命令句柄' }],
                difficulty: 3,
                focus: '数据和命令分开',
                body: [
                    '「输入框现在该被聚焦」不是长期状态。用户一点,焦点到了,这件事就结束了。ref 上的 focus() 表达这个动作。',
                    '若界面要显示「当前是否聚焦」,那是另一份可以渲染的事实,用事件把焦点变化写进 state。不要为了调用一个 DOM 方法把整个子树变成受控的布尔开关。',
                ],
            },
            {
                id: 'a-prop-drill',
                toc: '钻探和组合',
                title: '中间三层都只是把 theme 传下去,应该怎么改？',
                note: '中间层不认识 theme。',
                points: ['创建叶子的那一层已经能拿到 theme。', '用 children 把叶子放进外壳,外壳不接 theme。', '如果很多远叶子都要读,而且中间真的不该知道,再用 Context。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 4,
                focus: '组合优先于钻探,Context 不是第一反应',
                body: [
                    'Shell 只负责布局。Page 创建内容和 Shell,把内容作为 children 放进去。theme 在 Page 里用完,Shell 的参数列表里没有它。',
                    '当叶子分散在很多路由、创建点和使用点对不上,children 传不过去,Context 才合适。先用组合能解决的,不要先建 Provider。',
                ],
            },
            {
                id: 'a-duplicate',
                toc: '两份事实',
                title: '为什么「服务端数据再抄进本地 state」常常是错的？',
                note: '抄写会制造第二个所有者。',
                points: ['查询结果的所有者是数据层。', '组件要的是派生视图时,渲染时算。', '只有用户草稿才单独成为本地 state。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 4,
                focus: '服务端状态和 UI 状态的所有权',
                body: [
                    'effect 里把请求结果 set 进 state,刷新、失效、别的组件改了同一份数据,这层副本都不知道。加载和错误也会再写一套。',
                    '数据层已经有缓存和状态。组件直接读。用户正在编辑的副本是另一份事实,提交成功再写回数据层,而不是两套列表各改各的。',
                ],
            },
            {
                id: 'a-red-lines',
                toc: '不该出现的通道',
                title: '生产里哪些通信方式不该出现？',
                note: '三条常见红线。',
                points: ['不要用全局可变变量当渲染数据源。', '不要让兄弟通过 DOM 查询互相找节点来传数据。', '不要为了省一层 props 去改模块级单例。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 3,
                focus: '渲染必须能从输入复现',
                body: [
                    '模块级变量改了,React 不会渲染。下次碰巧渲染才看得见,测试之间还会互相污染。',
                    'querySelector 找兄弟的输入框,结构一变就断,服务端也没有这棵 DOM。数据走 props、URL 或 store,命令才走 ref。',
                ],
            },
        ],
    },
    {
        id: 'g-context',
        title: 'Context',
        blurb: 'Context 是依赖注入。它不自动跳过中间组件,也不适合高频大对象。',
        questions: [
            {
                id: 'a-ctx-is',
                toc: 'Context 注入什么',
                title: 'Context 解决的是钻探,还是性能？',
                note: '它让远叶子读到值,不负责减少渲染。',
                points: ['读者多、中间层不关心、变得不勤,才适合。', 'value 用 Object.is 比较。', '新对象会让所有消费者更新。'],
                related: [{ to: '/advanced/context', label: 'Context API' }],
                body: [
                    '主题、语言、当前用户会话适合 Context。它们变的次数少,读的地方多。把整个页面的 state 放进一个 value,任何字段变化都通知所有人。',
                    'value 的身份要稳住。用 useMemo 包对象,依赖只写真正的字段。不要在 Provider 的 JSX 里写 value={{ user }}。',
                ],
            },
            {
                id: 'a-ctx-skip',
                toc: '中间层不会自动跳过',
                title: 'Provider 下面的组件没有 useContext,为什么还是可能渲染？',
                note: '更新从提供值的位置走下来。',
                points: ['消费者一定能看到新值。', '中间组件默认会执行。', '跳过靠 children 槽或 memo,不是 Context 自带的。'],
                related: [{ to: '/advanced/context', label: 'Context API' }],
                difficulty: 4,
                focus: 'Context 的渲染范围',
                body: [
                    'Provider 的 value 变了,React 要找到消费者。沿途的组件函数会走,除非它们满足跳过条件。没写 useContext 不等于被跳过。',
                    '昂贵子树由 Provider 外面的父组件创建,作为 children 传入 Provider 下面的布局。布局即使渲染,放下的 children 引用不变,里面可以不重做。',
                ],
            },
            {
                id: 'a-ctx-split',
                toc: '拆 Provider',
                title: '一个 Context 里既有几乎不变的用户,又有频繁变的进度,应该怎么拆？',
                note: '按变化频率拆,而不是按文件拆。',
                points: ['不变的和常变的分成两个 value。', '只读用户的组件不要订阅进度。', '拆开之后仍要各自稳住对象身份。'],
                related: [{ to: '/advanced/context', label: 'Context API' }],
                difficulty: 4,
                focus: '订阅面和变化频率对齐',
                body: [
                    '一个 value 里放 user 和 progress,progress 每秒变,读 user 的头部也要看这个新 value。分成两个 Provider,头部只订阅用户。',
                    '这是 Context 能做的粒度。若字段很多、订阅组合更细,外部 store 的选择器更合适。不要为了拆而拆成十个几乎同时变的 Context。',
                ],
            },
            {
                id: 'a-ctx-default',
                toc: '默认值不是当前值',
                title: 'createContext 的默认值在什么时候才会被读到？',
                note: '有 Provider 时用的是 Provider 的 value。',
                points: ['默认值只在树上没有 Provider 时使用。', '它经常用来在测试或故事里兜底。', '不要把它当成「Provider 还没准备好时的加载值」。'],
                related: [{ to: '/advanced/context', label: 'Context API' }],
                difficulty: 3,
                focus: '默认值和 Provider 的关系',
                body: [
                    '组件在 Provider 里面,useContext 拿到的是最近 Provider 的 value,哪怕 value 是 null。默认值不会参与。',
                    '忘记包 Provider 时才会落到默认值。若默认值是一个空对象,消费者会把「没有提供者」误当成「用户是空的」,错误被藏住。可以让默认值是一个会抛错的读函数,专门暴露漏包。',
                ],
            },
            {
                id: 'a-ctx-update',
                toc: '更新函数放哪',
                title: '把 state 和 setState 放进同一个 Context value,有什么问题？',
                note: 'setState 稳定,state 常变。捆在一起会一起通知。',
                points: ['更新函数的身份通常不变。', '和 state 合成一个对象后,state 一变,只调用更新函数的组件也被通知。', '可以拆成状态 Context 和动作 Context。'],
                related: [{ to: '/advanced/context', label: 'Context API' }],
                difficulty: 4,
                focus: '稳定的动作和常变的数据不要绑成一个 value',
                body: [
                    '很多按钮只需要 dispatch,不需要读当前值。它们和 state 捆在一个对象里,每次状态变化都要渲染这些按钮。',
                    '动作放进单独的 Provider,value 是稳定的 dispatch。状态放另一个。按钮订阅动作,展示组件订阅状态。',
                ],
            },
            {
                id: 'a-ctx-memo-consumer',
                toc: '消费者里的计算',
                title: 'useContext 之后再做昂贵过滤,怎样避免每次无关 value 都重算？',
                note: '先缩小订阅,再考虑缓存。',
                points: ['最好根本不要订阅无关字段。', '订阅到的值用 useMemo 过滤,依赖是那份列表和关键字。', 'memo 包住消费者组件,挡不住它自己 useContext 引起的渲染。'],
                related: [{ to: '/advanced/context', label: 'Context API' }],
                difficulty: 5,
                focus: 'memo 挡不住自己订阅来的更新',
                body: [
                    '组件调用了 useContext,value 变了它就会执行。外面的 memo 比较的是 props,比较发生在这次由 Context 引起的渲染之前帮不上这个原因。',
                    '把过滤放进一个只接收列表的子组件,Context 留在很薄的父层,父层把列表当 props 传下去。子组件才能靠 memo 或 useMemo 跳过无关更新。',
                ],
            },
            {
                id: 'a-ctx-server',
                toc: 'Context 跨不过服务器边界',
                title: '客户端的 Context 能自动进服务器组件吗？',
                note: '服务器组件不在浏览器里读这次点击产生的 Context。',
                points: ['Context 是同一棵渲染树里的依赖注入。', '服务器组件在服务端执行,读不到浏览器里的 Provider。', '要传给服务器的是请求里的数据,不是客户端 Context。'],
                related: [
                    { to: '/advanced/context', label: 'Context API' },
                    { to: '/advanced/rsc-guide', label: 'RSC 梳理' },
                ],
                difficulty: 5,
                focus: 'Context 的树和 RSC 边界',
                body: [
                    'Provider 在客户端组件里,它下面的客户端孩子能读到。服务器组件的函数在服务端跑完才把描述传下来,它看不到用户后来在浏览器里改的 Context。',
                    '主题若要影响服务器输出的 HTML,得是请求时就知道的数据。交互后的主题切换是客户端状态。不要假设一个 React.createContext 在两端是同一份内存。',
                ],
            },
            {
                id: 'a-ctx-test',
                toc: '测试里提供 value',
                title: '测一个消费 Context 的组件,应该怎么包？',
                note: '给一个最小 Provider,不要启动整棵应用。',
                points: ['测试渲染时包上 Provider,value 用这则用例需要的数据。', '不断言默认值碰巧能工作。', '更新 value,看消费者是否呈现下一次的结果。'],
                related: [{ to: '/advanced/context', label: 'Context API' }],
                body: [
                    '组件假设树上有当前用户。测试里包一个 Provider,传入一个最小用户对象。不要为了这个去渲染完整布局。',
                    '再渲染一次,换 value,断言名字变了。这样把「订阅的是这份 value」锁住,而不是锁住应用里那个大 Provider 的实现。',
                ],
            },
        ],
    },
    {
        id: 'g-error',
        title: '错误边界',
        blurb: '边界接住的是子树渲染。事件和异步要自己处理。',
        questions: [
            {
                id: 'a-eb-what',
                toc: '接住哪类错误',
                title: '错误边界接得住哪些 throw,接不住哪些？',
                note: '看 throw 发生在渲染里还是回调里。',
                points: ['子树渲染、构造和提交阶段的同步异常可以接住。', '事件处理函数里的异常不进入边界。', 'setTimeout、Promise 拒绝也不进入。'],
                related: [{ to: '/advanced/error-boundary', label: 'Error Boundary' }],
                difficulty: 4,
                focus: '失败通道',
                body: [
                    '渲染函数抛出,协调过程要把这棵子树换成降级 UI,否则整页卸掉。类组件的 getDerivedStateFromError 提供这份降级 state。',
                    '按钮里的 throw 发生在浏览器事件里,React 没有把它送进渲染。要有自己的 try,或让错误上报。不要以为套了边界,点击就安全了。',
                ],
            },
            {
                id: 'a-eb-class',
                toc: '为什么还是类',
                title: '为什么不能用函数组件写错误边界？',
                note: '需要在渲染期提供降级 state 的生命周期。',
                points: ['getDerivedStateFromError 在渲染阶段给出下一次 UI。', 'componentDidCatch 用来记录。', '函数组件没有对应挂钩。'],
                related: [
                    { to: '/advanced/error-boundary', label: 'Error Boundary' },
                    { to: '/basics/fn-vs-class-guide', label: '函数组件与类组件' },
                ],
                difficulty: 3,
                focus: '能力边界不是风格选择',
                body: [
                    '降级 UI 必须在同一次错误处理里变成下一次渲染的 state。这是类的静态方法在做的事。函数组件若在渲染里 try/catch,只能接住自己这个函数里的 throw,接不住孩子。',
                    '新代码仍用函数组件。整个应用或一块功能的外层补一个很薄的类边界即可。',
                ],
            },
            {
                id: 'a-eb-grain',
                toc: '粒度',
                title: '错误边界应该包住整页,还是包住一块功能？',
                note: '失败半径要和功能半径一致。',
                points: ['包得太大,一块挂了整页都变成降级。', '包得太碎,用户看不到关联功能已经不可用。', '能独立重试的区域各自一个边界。'],
                related: [{ to: '/advanced/error-boundary', label: 'Error Boundary' }],
                difficulty: 4,
                focus: '降级粒度',
                body: [
                    '侧栏挂了不该让主表单一起消失。主表单和它的提交结果是一块,可以共用一个边界。',
                    '每个单元格一个边界会让页面布满互不相干的错误提示,也让错误之间的因果关系看不出来。按用户能单独重试的单位来包。',
                ],
            },
            {
                id: 'a-eb-reset',
                toc: '重置',
                title: '点了重试立刻又进入降级,通常是什么原因？',
                note: '抛错的输入还在。',
                points: ['重置清的是边界自己的错误 state。', '父级 props、路由参数没变,渲染会再抛。', '要一起换掉导致抛错的那份输入。'],
                related: [{ to: '/advanced/error-boundary', label: 'Error Boundary' }],
                difficulty: 4,
                focus: '恢复的是状态还是输入',
                body: [
                    '边界把 hasError 设回 false,孩子用同一份坏数据再渲染,又抛。按钮不是没点上。',
                    '重试时换 key、清掉那条数据,或回到上一条可用的路由。只清错误标志,等于让同一次失败再演一遍。',
                ],
            },
            {
                id: 'a-eb-event',
                toc: '事件错误自己处理',
                title: '提交按钮里的请求失败,为什么页面没有换成错误边界的 UI？',
                note: '请求失败通常不是渲染期 throw。',
                points: ['Promise 拒绝不是渲染异常。', '把错误写进 state,由正常渲染显示错误。', '只有渲染时读到坏数据再抛,边界才接得到。'],
                related: [{ to: '/advanced/error-boundary', label: 'Error Boundary' }],
                difficulty: 3,
                focus: '可预期失败和渲染崩溃',
                body: [
                    '校验失败、接口 400,是业务流程。用状态显示在表单旁边,用户可以改完再提交。这不是崩溃。',
                    '渲染假设数据一定有 id,结果是 undefined,接着读属性抛出,这才是边界的事。更好的做法是渲染前判断缺数据,给出空状态,而不是靠抛来驱动 UI。',
                ],
            },
            {
                id: 'a-eb-log',
                toc: '记录放哪',
                title: 'componentDidCatch 和 getDerivedStateFromError 各做什么？',
                note: '一个改 UI,一个做副作用。',
                points: ['getDerivedStateFromError 必须是纯的,只返回 state。', 'componentDidCatch 里上报日志。', '不要在派生 state 的方法里发请求。'],
                related: [{ to: '/advanced/error-boundary', label: 'Error Boundary' }],
                difficulty: 3,
                focus: '渲染期方法和提交期方法',
                body: [
                    '派生 state 会在渲染阶段调用。在里面上报,可能重复,也混进了副作用。它只回答「下一次画什么」。',
                    'DidCatch 在提交之后,适合把错误和组件栈送给日志系统。上报失败不应该再抛,否则边界自己又失败了。',
                ],
            },
            {
                id: 'a-eb-ssr',
                toc: '服务端错误',
                title: '服务端渲染抛错,会进浏览器里这个错误边界吗？',
                note: '服务端的失败发生在另一端。',
                points: ['服务端渲染的异常由服务端处理。', '浏览器里的边界只看见水合之后的客户端渲染。', '两端都要有自己的降级,不能假设类实例跨过了网络。'],
                related: [{ to: '/advanced/error-boundary', label: 'Error Boundary' }],
                difficulty: 5,
                focus: '错误发生在哪一端',
                body: [
                    '服务端函数抛出,响应可能是错误页或流里的错误片段。浏览器还没有那个类实例,componentDidCatch 不会在用户机器上跑。',
                    '水合成功之后,客户端再抛,才进入页面上的边界。所以「有错误边界就不会白屏」只覆盖客户端渲染这条通道。',
                ],
            },
            {
                id: 'a-eb-null',
                toc: '不要吞掉',
                title: '边界渲染 null,和渲染一块说明加重置,有什么差别？',
                note: '失败要对用户可见、可恢复。',
                points: ['null 会让一块区域突然消失,原因不明。', '降级 UI 说明这里失败了,并给出重试或返回。', '日志仍然要上报,不能只靠界面。'],
                related: [{ to: '/advanced/error-boundary', label: 'Error Boundary' }],
                body: [
                    '返回 null 能阻止白屏,但用户以为功能没了。一块小的说明加上重试,失败半径才完整。',
                    '界面上的重试不能代替日志。没有记录的话,只能等用户描述「那一块不见了」。',
                ],
            },
        ],
    },
    {
        id: 'g-compose',
        title: '组合',
        blurb: '用组装代替布尔开关。插槽让中间层保持无知。',
        questions: [
            {
                id: 'a-bool',
                toc: '布尔开关会膨胀',
                title: '为什么一个组件上的 isThread、isEditing、isDM 会越来越难改？',
                note: '每个开关都把所有分支乘一遍。',
                points: ['布尔组合出调用方自己也说不清的状态。', '显式的变体各自组装需要的部分。', '共用的输入框、按钮做成小块,而不是一个上帝组件。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 3,
                focus: '变体用组合表达',
                body: [
                    '三个布尔有八种组合,其中一些根本不该存在,例如既是编辑又是转发。条件堆在一个 return 里,改一个变体会碰到别的分支。',
                    'ThreadComposer 和 EditComposer 各自写清自己有哪些部分。重复的输入框抽出去。调用处一眼能看出这是哪一种,而不是猜开关。',
                ],
            },
            {
                id: 'a-slot',
                toc: '插槽',
                title: 'children 和 render props,什么时候用哪一个？',
                note: '只是组装结构用 children。要把数据交回去再用渲染函数。',
                points: ['children 适合静态结构。', '父组件要把条目、下标交给调用方时,渲染函数说得清。', '不要同时做一套 renderHeader、renderFooter 开关。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 3,
                focus: '数据向下和结构组装',
                body: [
                    '布局外壳不需要知道里面是什么,children 最直接。列表要把每一项的数据交给外面画,外面需要参数,这时渲染函数是合理的。',
                    '五个 renderXxx 加几个布尔,调用方要读完组件实现才知道会画什么。改成子组件组装,结构就是调用处的那棵 JSX。',
                ],
            },
            {
                id: 'a-compound',
                toc: '复合组件',
                title: '复合组件的状态放在哪,才让外面的按钮也能提交？',
                note: '状态在提供者上,不锁在视觉上的那一层框里。',
                points: ['Provider 持有 state 和动作。', '框、输入、按钮都是可选的组装块。', '提交按钮可以画在对话框底部,只要还在 Provider 里面。'],
                related: [{ to: '/advanced/component-comm-practice', label: '通信实战' }],
                difficulty: 4,
                focus: '状态边界和视觉边界可以不一致',
                body: [
                    '若 state 写在输入框组件内部,对话框底部的按钮拿不到它,就会出现把 state 同步上去的 effect。把 state 抬到 Provider,输入框和按钮都读这份上下文。',
                    '框只是 form 标签。预览、按钮可以放在框外面,仍然在同一个提供者里。视觉上不嵌套,数据上仍然在一块。',
                ],
            },
            {
                id: 'a-provider-swap',
                toc: '换提供者',
                title: '同一套输入 UI,怎样分别接本地草稿和全局同步的频道？',
                note: 'UI 只依赖状态、动作和元信息这套接口。',
                points: ['输入组件不知道 state 来自 useState 还是 store。', '不同 Provider 实现同一套接口。', '换数据源时不改输入框。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 5,
                focus: '依赖注入',
                body: [
                    '接口分成 state、actions、meta。本地转发消息用 useState。频道用已有的 store。两个 Provider 都把这三样传下去。',
                    '输入框只调用 actions.update。它不必知道要不要发网络请求。请求放在频道那个 Provider 的 submit 里。这样测试可以用一个假的 Provider,不必启动 store。',
                ],
            },
            {
                id: 'a-slot-memo',
                toc: '插槽稳住引用',
                title: '为什么把昂贵子树作为 children 传入,中间层 setState 时它可能不重做？',
                note: '元素在更上层创建。',
                points: ['父组件创建元素,中间层只放下。', '中间层渲染不等于重新调用子组件函数。', '中间层若自己再写一遍 JSX,引用就变了。'],
                related: [{ to: '/advanced/component-comm-guide', label: '通信梳理' }],
                difficulty: 4,
                focus: '元素在哪一层创建',
                body: [
                    'Page 渲染 Expensive 和 Shell。Shell 的 state 变了,Page 不一定重新执行,children 还是上一次那份。Shell 原样 return children,Expensive 可以跳过。',
                    '在 Shell 里写成 <Expensive />,每次 Shell 渲染都新建描述,跳过就不成立。组合把创建权留在拥有数据的那一层。',
                ],
            },
            {
                id: 'a-variant',
                toc: '显式变体',
                title: '一个组件的 mode="edit" | "view" | "forward" 和三个组件,怎么选？',
                note: '模式一多,显式变体更清楚。',
                points: ['两种很接近的外观可以留在一个组件里用少量参数。', '结构不同的模式拆成变体,各自组装。', '调用处应该能看出这次画的是哪一种。'],
                related: [{ to: '/advanced/component-comm-playground', label: '通信演练' }],
                difficulty: 3,
                focus: 'API 是否把不可能的状态留了出来',
                body: [
                    '只是按钮文案不同,不值得拆文件。编辑态没有附件、转发态多一个选择器,它们的树已经不同,硬塞进 mode 会留下永远走不到又必须处理的分支。',
                    '变体可以共用输入框。共用小块,不共用一个带十个开关的父组件。',
                ],
            },
            {
                id: 'a-context-vs-props',
                toc: '复合组件里的 Context',
                title: '复合组件内部用 Context,和业务里滥用 Context 有什么差别？',
                note: '范围要小,而且是实现细节。',
                points: ['Context 包在这一组组件内部。', '外面仍然用 props 或 Provider 的明确接口。', '不要把复合组件的内部 Context 出口到业务各处。'],
                related: [{ to: '/advanced/context', label: 'Context API' }],
                difficulty: 4,
                focus: 'Context 的作用域',
                body: [
                    'Tabs 和 TabPanel 之间用内部 Context 对上选中项,调用方不用把 selected 传给每一个面板。这个 Context 的文件不导出给业务页面乱用。',
                    '业务页面再把整个应用 state 放进同一个 Context,范围和变化频率都失控。内部通信的 Context 和全局依赖注入不是同一个决定。',
                ],
            },
            {
                id: 'a-compose-test',
                toc: '变体更好测',
                title: '为什么显式变体比布尔矩阵更好测？',
                note: '每种变体的渲染结果是确定的。',
                points: ['一个测试渲染一种变体。', '不需要覆盖互斥开关的非法组合。', '共用小块单独测行为,变体测组装。'],
                related: [{ to: '/advanced/component-comm-practice', label: '通信实战' }],
                body: [
                    'isEditing 且 isForwarding 这种用例不该存在,但布尔 API 允许它,测试就得决定这时画什么。变体 API 让这种输入写不出来。',
                    '输入框的测试看值变化和提交。编辑变体的测试只看它有没有保存和取消,没有附件。失败时能看出是小块坏了还是组装错了。',
                ],
            },
        ],
    },
    {
        id: 'g-data',
        title: '数据边界',
        blurb: '声明式数据、缓存和组件 state 不要各写一份。',
        questions: [
            {
                id: 'a-relay-decl',
                toc: '声明式取数',
                title: 'Relay 这类数据层和在 effect 里 fetch 再 setState,差在哪？',
                note: '组件声明需要什么,数据层负责缓存和请求。',
                points: ['组件不拥有「请求中的那份列表副本」。', '同一份数据被多处声明时可以复用缓存。', '更新之后失效的是数据层,不是每个组件自己的 state。'],
                related: [{ to: '/advanced/relay', label: 'Relay' }],
                difficulty: 4,
                focus: '数据所有权和 UI 所有权',
                body: [
                    'effect 取数把加载、错误、结果都写进组件。第二个组件要用同一份数据,就再请求一次,或再抬一层 state。声明式查询让数据层看到重复,只打一次,两边读缓存。',
                    '变更成功后让对应查询失效。组件下一次读到新数据,而不是记得去 set 某一个本地数组。',
                ],
            },
            {
                id: 'a-fragment-data',
                toc: '片段跟着组件',
                title: '为什么数据片段应该跟着要用它的组件走,而不是在页面顶上取一整份再钻探下去？',
                note: '组件搬走时,数据需求跟着走。',
                points: ['顶上取全部字段,中间层只为转发。', '片段写在用字段的组件旁边,重构时不会漏。', '页面负责把这些需求合成一次请求,而不是每个组件各请求一遍。'],
                related: [{ to: '/advanced/relay', label: 'Relay' }],
                difficulty: 5,
                focus: '数据需求和 UI 结构对齐',
                body: [
                    '卡片只用名字和价格,详情才要库存。都在页面查询里写完,卡片一挪走,页面查询还留着无用字段,新页面又容易漏字段。',
                    '片段放在卡片组件上。页面把子组件的片段收进自己的查询。组件搬到别的页面,片段一起走,数据层仍能合成请求,而不是每个卡片发一次。',
                ],
            },
            {
                id: 'a-waterfall-data',
                toc: '不要串行等',
                title: '父组件 await 完再渲染子组件,子组件再 await,问题在哪？',
                note: '彼此独立的数据不该排成一列。',
                points: ['子组件要等父组件的等待结束才开始自己的等待。', '没有依赖的请求应该一起开始。', '有依赖的请求在拿到 id 之后立刻接上,不要等无关的兄弟。'],
                related: [{ to: '/performance/architecture-guide', label: '架构关键路径' }],
                difficulty: 4,
                focus: '数据瀑布',
                body: [
                    '页面先等用户,再渲染侧栏,侧栏再等菜单。两段网络变成相加。侧栏和用户没有依赖,就该同时开始。',
                    '菜单依赖用户 id 时,用户一到就发起菜单请求,不要等页面上其它无关请求。组件结构要允许这些请求并行,而不是把 await 写在父组件函数的最前面挡住整棵树。',
                ],
            },
            {
                id: 'a-stale-view',
                toc: '乐观和回滚',
                title: '乐观更新之后请求失败,界面应该回到哪？',
                note: '临时值和服务器事实要能分开。',
                points: ['乐观值只在请求进行中显示。', '失败后回到服务器确认过的那一份。', '不要把乐观值写进唯一的那份 state 然后丢掉旧值。'],
                related: [{ to: '/advanced/component-comm-practice', label: '通信实战' }],
                difficulty: 4,
                focus: '临时事实和已提交事实',
                body: [
                    '先把评论插进列表,请求失败如果旧列表已经没了,就无法完整撤掉。保留已确认的列表,另存一份待确认的修改。',
                    '成功后再把待确认的修改收进已确认的数据,或让数据层返回新的正规结果替换。失败只清掉待确认的那份,并说明没有发出去。',
                ],
            },
            {
                id: 'a-normalized',
                toc: '按 id 存',
                title: '同一条用户在列表和详情里各存一份对象,会出什么问题？',
                note: '身份相同的实体不要有两份互相独立的副本。',
                points: ['改了详情里的名字,列表还是旧的。', '按 id 放进一份表,列表只存 id。', 'UI 状态仍然可以局部拥有,实体数据不要复制。'],
                related: [{ to: '/advanced/relay', label: 'Relay' }],
                difficulty: 4,
                focus: '实体身份',
                body: [
                    '两份对象在内存里没有关联。一次更新只碰到其中一份,另一处要靠刷新才对齐。用户会看到同一人两个名字。',
                    '表里一份用户,列表渲染时按 id 去取。详情改的是这份。组件自己的展开、草稿仍然局部存放,不进这张表。',
                ],
            },
            {
                id: 'a-error-empty',
                toc: '空、加载、错误',
                title: '加载、空列表和错误,为什么不能都用一个 data === null 表示？',
                note: '三种界面是三种事实。',
                points: ['还没有结果,是加载。', '结果是空数组,是空状态。', '请求失败,是错误,可能同时还有上一次的成功数据。'],
                related: [{ to: '/advanced/component-comm-practice', label: '通信实战' }],
                difficulty: 3,
                focus: '状态要能区分',
                body: [
                    'null 同时表示没加载完和加载完但没有数据,界面只能猜。空状态会在加载时闪一下,错误也被画成「暂无数据」。',
                    '保留上一次成功的数据,同时记下正在刷新和错误。用户还能看见旧列表,并知道这次刷新没成功。不要为了显示错误把旧数据清掉。',
                ],
            },
            {
                id: 'a-colocate',
                toc: '请求靠近使用处',
                title: '为什么数据需求放在页面文件顶上的一个大函数里,组件一多就会失真？',
                note: '使用字段的地方应该能看见自己的需求。',
                points: ['大函数知道所有字段,组件只接 props。', '删掉一块 UI,请求常常忘了删字段。', '需求跟着组件走,页面负责组合。'],
                related: [{ to: '/advanced/relay', label: 'Relay' }],
                difficulty: 3,
                focus: '需求的局部性',
                body: [
                    '顶上的函数成为唯一知道数据形状的地方。组件变成纯展示,看起来整齐,但改一个字段要在两个距离很远的地方一起改。',
                    '组件旁边写下它要的字段,页面把它们合起来。展示组件仍然可以只接已经准备好的 props,那是边界,不是把所有知识都堆进页面容器。',
                ],
            },
            {
                id: 'a-mock-boundary',
                toc: 'mock 不要泄漏',
                title: '演练里的 mock 数据层,怎样才不会把假数据写进组件？',
                note: '组件依赖数据接口,不依赖假数据从哪来。',
                points: ['组件调用同一套读取函数或查询。', '开发环境把实现换成 mock。', '组件里写死的假数组不会在接上真接口时被记得删掉。'],
                related: [{ to: '/advanced/relay', label: 'Relay' }],
                body: [
                    '组件如果 import 一份本地数组,接上接口时要改组件。读取函数或查询放在边界外,组件只声明需要什么。',
                    'mock 换掉的是那个边界的实现。测试传入最小数据,生产走真实实现。组件测试不必知道存储在哪。',
                ],
            },
        ],
    },
];

export const ADVANCED_GROUPS = numberGroups(GROUPS);
export const ADVANCED_COUNT = countQuestions(ADVANCED_GROUPS);
